import { RecipeModel } from './models';

export const RECIPES: RecipeModel[] = [
  {
    id: 1,
    name: 'Spaghetti Carbonara',
    description: 'A classic Italian pasta dish.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Spaghetti+Carbonara',
    ingredients: [
      { name: 'Spaghetti', quantity: 200, unit: 'g' },
      { name: 'Guanciale', quantity: 100, unit: 'g' },
      { name: 'Egg Yolks', quantity: 4, unit: 'each' },
      { name: 'Pecorino Romano Cheese', quantity: 50, unit: 'g' },
      { name: 'Black Pepper', quantity: 1, unit: 'tsp' },
    ],
  },
  {
    id: 2,
    name: 'Caprese Salad',
    description: 'A simple and refreshing Italian salad.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Caprese+Salad',
    ingredients: [
      { name: 'Tomatoes', quantity: 4, unit: 'each' },
      { name: 'Fresh Mozzarella', quantity: 200, unit: 'g' },
      { name: 'Fresh Basil', quantity: 1, unit: 'bunch' },
      { name: 'Extra Virgin Olive Oil', quantity: 2, unit: 'tbsp' },
    ],
  },
  {
    id: 3,
    name: 'Chicken Tikka Masala',
    description: 'Creamy tomato curry with tender chicken.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Chicken+Tikka+Masala',
    ingredients: [
      { name: 'Chicken Thighs', quantity: 600, unit: 'g' },
      { name: 'Greek Yogurt', quantity: 150, unit: 'ml' },
      { name: 'Tomato Passata', quantity: 400, unit: 'ml' },
      { name: 'Heavy Cream', quantity: 100, unit: 'ml' },
      { name: 'Garam Masala', quantity: 2, unit: 'tsp' },
    ],
  },
  {
    id: 4,
    name: 'Beef Tacos',
    description: 'Seasoned ground beef in soft tortillas.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Beef+Tacos',
    ingredients: [
      { name: 'Ground Beef', quantity: 500, unit: 'g' },
      { name: 'Corn Tortillas', quantity: 8, unit: 'each' },
      { name: 'Onion', quantity: 1, unit: 'each' },
      { name: 'Cheddar Cheese', quantity: 100, unit: 'g' },
      { name: 'Taco Seasoning', quantity: 2, unit: 'tbsp' },
    ],
  },
  {
    id: 5,
    name: 'Vegetable Stir-Fry',
    description: 'Quick wok-fried vegetables with soy and ginger.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Vegetable+Stir-Fry',
    ingredients: [
      { name: 'Broccoli', quantity: 200, unit: 'g' },
      { name: 'Bell Pepper', quantity: 2, unit: 'each' },
      { name: 'Soy Sauce', quantity: 3, unit: 'tbsp' },
      { name: 'Fresh Ginger', quantity: 1, unit: 'tbsp' },
      { name: 'Sesame Oil', quantity: 1, unit: 'tsp' },
    ],
  },
  {
    id: 6,
    name: 'Margherita Pizza',
    description: 'Thin crust with tomato, mozzarella, and basil.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Margherita+Pizza',
    ingredients: [
      { name: 'Pizza Dough', quantity: 1, unit: 'each' },
      { name: 'Crushed Tomatoes', quantity: 200, unit: 'g' },
      { name: 'Fresh Mozzarella', quantity: 250, unit: 'g' },
      { name: 'Fresh Basil', quantity: 0.5, unit: 'bunch' },
      { name: 'Olive Oil', quantity: 1, unit: 'tbsp' },
    ],
  },
  {
    id: 7,
    name: 'French Onion Soup',
    description: 'Caramelized onions in rich broth with melted cheese.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=French+Onion+Soup',
    ingredients: [
      { name: 'Yellow Onions', quantity: 6, unit: 'each' },
      { name: 'Beef Stock', quantity: 1, unit: 'L' },
      { name: 'Butter', quantity: 50, unit: 'g' },
      { name: 'Gruyère Cheese', quantity: 150, unit: 'g' },
      { name: 'Baguette', quantity: 0.5, unit: 'each' },
    ],
  },
  {
    id: 8,
    name: 'Salmon with Dill',
    description: 'Baked salmon fillets with lemon and fresh dill.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Salmon+with+Dill',
    ingredients: [
      { name: 'Salmon Fillets', quantity: 4, unit: 'each' },
      { name: 'Lemon', quantity: 1, unit: 'each' },
      { name: 'Fresh Dill', quantity: 2, unit: 'tbsp' },
      { name: 'Olive Oil', quantity: 2, unit: 'tbsp' },
      { name: 'Salt', quantity: 0.5, unit: 'tsp' },
    ],
  },
  {
    id: 9,
    name: 'Mushroom Risotto',
    description: 'Creamy arborio rice with sautéed mushrooms.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Mushroom+Risotto',
    ingredients: [
      { name: 'Arborio Rice', quantity: 300, unit: 'g' },
      { name: 'Mixed Mushrooms', quantity: 400, unit: 'g' },
      { name: 'Vegetable Stock', quantity: 1, unit: 'L' },
      { name: 'White Wine', quantity: 125, unit: 'ml' },
      { name: 'Parmesan Cheese', quantity: 50, unit: 'g' },
    ],
  },
  {
    id: 10,
    name: 'Greek Salad',
    description: 'Crisp vegetables with feta and olives.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Greek+Salad',
    ingredients: [
      { name: 'Cucumber', quantity: 1, unit: 'each' },
      { name: 'Tomatoes', quantity: 3, unit: 'each' },
      { name: 'Feta Cheese', quantity: 150, unit: 'g' },
      { name: 'Kalamata Olives', quantity: 100, unit: 'g' },
      { name: 'Red Wine Vinegar', quantity: 2, unit: 'tbsp' },
    ],
  },
  {
    id: 11,
    name: 'Pad Thai',
    description: 'Rice noodles with shrimp, peanuts, and lime.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Pad+Thai',
    ingredients: [
      { name: 'Rice Noodles', quantity: 200, unit: 'g' },
      { name: 'Shrimp', quantity: 300, unit: 'g' },
      { name: 'Tamarind Paste', quantity: 2, unit: 'tbsp' },
      { name: 'Bean Sprouts', quantity: 100, unit: 'g' },
      { name: 'Roasted Peanuts', quantity: 50, unit: 'g' },
    ],
  },
  {
    id: 12,
    name: 'Beef Bourguignon',
    description: 'Slow-braised beef in red wine with vegetables.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Beef+Bourguignon',
    ingredients: [
      { name: 'Beef Chuck', quantity: 1, unit: 'kg' },
      { name: 'Red Wine', quantity: 750, unit: 'ml' },
      { name: 'Pearl Onions', quantity: 200, unit: 'g' },
      { name: 'Carrots', quantity: 3, unit: 'each' },
      { name: 'Button Mushrooms', quantity: 250, unit: 'g' },
    ],
  },
  {
    id: 13,
    name: 'Shakshuka',
    description: 'Eggs poached in spiced tomato and pepper sauce.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Shakshuka',
    ingredients: [
      { name: 'Crushed Tomatoes', quantity: 400, unit: 'g' },
      { name: 'Bell Peppers', quantity: 2, unit: 'each' },
      { name: 'Eggs', quantity: 6, unit: 'each' },
      { name: 'Cumin', quantity: 1, unit: 'tsp' },
      { name: 'Feta Cheese', quantity: 80, unit: 'g' },
    ],
  },
  {
    id: 14,
    name: 'Chicken Caesar Salad',
    description: 'Romaine, grilled chicken, parmesan, and croutons.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Chicken+Caesar+Salad',
    ingredients: [
      { name: 'Romaine Lettuce', quantity: 2, unit: 'heads' },
      { name: 'Chicken Breast', quantity: 2, unit: 'each' },
      { name: 'Parmesan', quantity: 50, unit: 'g' },
      { name: 'Caesar Dressing', quantity: 80, unit: 'ml' },
      { name: 'Croutons', quantity: 100, unit: 'g' },
    ],
  },
  {
    id: 15,
    name: 'Vegetable Lasagna',
    description: 'Layered pasta with ricotta, spinach, and marinara.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Vegetable+Lasagna',
    ingredients: [
      { name: 'Lasagna Sheets', quantity: 12, unit: 'each' },
      { name: 'Ricotta', quantity: 400, unit: 'g' },
      { name: 'Spinach', quantity: 300, unit: 'g' },
      { name: 'Marinara Sauce', quantity: 600, unit: 'ml' },
      { name: 'Mozzarella', quantity: 200, unit: 'g' },
    ],
  },
  {
    id: 16,
    name: 'Thai Green Curry',
    description: 'Coconut curry with chicken and Thai basil.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Thai+Green+Curry',
    ingredients: [
      { name: 'Chicken Breast', quantity: 500, unit: 'g' },
      { name: 'Green Curry Paste', quantity: 3, unit: 'tbsp' },
      { name: 'Coconut Milk', quantity: 400, unit: 'ml' },
      { name: 'Thai Basil', quantity: 1, unit: 'cup' },
      { name: 'Fish Sauce', quantity: 1, unit: 'tbsp' },
    ],
  },
  {
    id: 17,
    name: 'Banana Bread',
    description: 'Moist loaf sweetened with ripe bananas.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Banana+Bread',
    ingredients: [
      { name: 'Ripe Bananas', quantity: 3, unit: 'each' },
      { name: 'All-Purpose Flour', quantity: 250, unit: 'g' },
      { name: 'Sugar', quantity: 150, unit: 'g' },
      { name: 'Eggs', quantity: 2, unit: 'each' },
      { name: 'Butter', quantity: 80, unit: 'g' },
    ],
  },
  {
    id: 18,
    name: 'Chocolate Chip Cookies',
    description: 'Classic chewy cookies with dark chocolate chunks.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Chocolate+Chip+Cookies',
    ingredients: [
      { name: 'Butter', quantity: 115, unit: 'g' },
      { name: 'Brown Sugar', quantity: 150, unit: 'g' },
      { name: 'Flour', quantity: 220, unit: 'g' },
      { name: 'Chocolate Chips', quantity: 200, unit: 'g' },
      { name: 'Vanilla Extract', quantity: 1, unit: 'tsp' },
    ],
  },
  {
    id: 19,
    name: 'Overnight Oats',
    description: 'No-cook oats with yogurt and berries.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Overnight+Oats',
    ingredients: [
      { name: 'Rolled Oats', quantity: 80, unit: 'g' },
      { name: 'Milk', quantity: 200, unit: 'ml' },
      { name: 'Greek Yogurt', quantity: 100, unit: 'g' },
      { name: 'Mixed Berries', quantity: 100, unit: 'g' },
      { name: 'Honey', quantity: 1, unit: 'tbsp' },
    ],
  },
  {
    id: 20,
    name: 'Avocado Toast',
    description: 'Smashed avocado on sourdough with chili flakes.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Avocado+Toast',
    ingredients: [
      { name: 'Sourdough Bread', quantity: 4, unit: 'slices' },
      { name: 'Avocados', quantity: 2, unit: 'each' },
      { name: 'Lemon Juice', quantity: 1, unit: 'tbsp' },
      { name: 'Red Pepper Flakes', quantity: 0.5, unit: 'tsp' },
      { name: 'Sea Salt', quantity: 0.25, unit: 'tsp' },
    ],
  },
  {
    id: 21,
    name: 'Fish and Chips',
    description: 'Beer-battered cod with crispy fries.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Fish+and+Chips',
    ingredients: [
      { name: 'Cod Fillets', quantity: 4, unit: 'each' },
      { name: 'Russet Potatoes', quantity: 800, unit: 'g' },
      { name: 'Beer', quantity: 200, unit: 'ml' },
      { name: 'Flour', quantity: 200, unit: 'g' },
      { name: 'Vegetable Oil', quantity: 1, unit: 'L' },
    ],
  },
  {
    id: 22,
    name: 'Chicken Noodle Soup',
    description: 'Comforting broth with chicken, carrots, and egg noodles.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Chicken+Noodle+Soup',
    ingredients: [
      { name: 'Chicken Thighs', quantity: 500, unit: 'g' },
      { name: 'Chicken Stock', quantity: 1.5, unit: 'L' },
      { name: 'Egg Noodles', quantity: 200, unit: 'g' },
      { name: 'Carrots', quantity: 2, unit: 'each' },
      { name: 'Celery', quantity: 2, unit: 'stalks' },
    ],
  },
  {
    id: 23,
    name: 'Quinoa Buddha Bowl',
    description: 'Grain bowl with roasted vegetables and tahini.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Quinoa+Buddha+Bowl',
    ingredients: [
      { name: 'Quinoa', quantity: 200, unit: 'g' },
      { name: 'Sweet Potato', quantity: 2, unit: 'each' },
      { name: 'Chickpeas', quantity: 400, unit: 'g' },
      { name: 'Kale', quantity: 100, unit: 'g' },
      { name: 'Tahini', quantity: 2, unit: 'tbsp' },
    ],
  },
  {
    id: 24,
    name: 'Eggplant Parmesan',
    description: 'Breaded eggplant layered with tomato sauce and cheese.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Eggplant+Parmesan',
    ingredients: [
      { name: 'Eggplant', quantity: 2, unit: 'each' },
      { name: 'Marinara Sauce', quantity: 500, unit: 'ml' },
      { name: 'Mozzarella', quantity: 250, unit: 'g' },
      { name: 'Breadcrumbs', quantity: 150, unit: 'g' },
      { name: 'Eggs', quantity: 2, unit: 'each' },
    ],
  },
  {
    id: 25,
    name: 'Beef Chili',
    description: 'Hearty chili with beans and warm spices.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Beef+Chili',
    ingredients: [
      { name: 'Ground Beef', quantity: 600, unit: 'g' },
      { name: 'Kidney Beans', quantity: 400, unit: 'g' },
      { name: 'Crushed Tomatoes', quantity: 800, unit: 'g' },
      { name: 'Chili Powder', quantity: 2, unit: 'tbsp' },
      { name: 'Onion', quantity: 1, unit: 'each' },
    ],
  },
  {
    id: 26,
    name: 'Cobb Salad',
    description: 'Chopped salad with chicken, bacon, egg, and blue cheese.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Cobb+Salad',
    ingredients: [
      { name: 'Mixed Greens', quantity: 200, unit: 'g' },
      { name: 'Cooked Chicken', quantity: 200, unit: 'g' },
      { name: 'Bacon', quantity: 100, unit: 'g' },
      { name: 'Hard-Boiled Eggs', quantity: 2, unit: 'each' },
      { name: 'Blue Cheese', quantity: 80, unit: 'g' },
    ],
  },
  {
    id: 27,
    name: 'Lemon Ricotta Pancakes',
    description: 'Fluffy pancakes with citrus and creamy ricotta.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Lemon+Ricotta+Pancakes',
    ingredients: [
      { name: 'Ricotta', quantity: 200, unit: 'g' },
      { name: 'Flour', quantity: 150, unit: 'g' },
      { name: 'Lemon Zest', quantity: 1, unit: 'tbsp' },
      { name: 'Eggs', quantity: 2, unit: 'each' },
      { name: 'Milk', quantity: 100, unit: 'ml' },
    ],
  },
  {
    id: 28,
    name: 'Miso Ramen',
    description: 'Rich miso broth with noodles, egg, and scallions.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Miso+Ramen',
    ingredients: [
      { name: 'Ramen Noodles', quantity: 400, unit: 'g' },
      { name: 'Miso Paste', quantity: 3, unit: 'tbsp' },
      { name: 'Vegetable Stock', quantity: 1.2, unit: 'L' },
      { name: 'Soft-Boiled Eggs', quantity: 4, unit: 'each' },
      { name: 'Scallions', quantity: 4, unit: 'each' },
    ],
  },
  {
    id: 29,
    name: 'Apple Crisp',
    description: 'Baked apples under a buttery oat topping.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Apple+Crisp',
    ingredients: [
      { name: 'Apples', quantity: 6, unit: 'each' },
      { name: 'Rolled Oats', quantity: 100, unit: 'g' },
      { name: 'Brown Sugar', quantity: 80, unit: 'g' },
      { name: 'Butter', quantity: 80, unit: 'g' },
      { name: 'Cinnamon', quantity: 1, unit: 'tsp' },
    ],
  },
  {
    id: 30,
    name: 'Garlic Butter Shrimp',
    description: 'Quick skillet shrimp with garlic, lemon, and parsley.',
    imgUrl: 'https://via.placeholder.com/300x200.png?text=Garlic+Butter+Shrimp',
    ingredients: [
      { name: 'Large Shrimp', quantity: 500, unit: 'g' },
      { name: 'Butter', quantity: 60, unit: 'g' },
      { name: 'Garlic Cloves', quantity: 4, unit: 'each' },
      { name: 'Lemon', quantity: 0.5, unit: 'each' },
      { name: 'Fresh Parsley', quantity: 2, unit: 'tbsp' },
    ],
  },
];
